version: '2'

services:
  mq:
    image: rabbitmq:3.6.10-management
    expose:
      - "15671"
      - "15672"
 

  api:
    build: ./server/
    ports:
      - 80:8080
    environment:
      - AMQP_URL=amqp://mq/
    links:
      - mq
    depends_on:
      - mq

  cowsay:
    build: ./cowsay/
    environment:
      - AMQP_URL=amqp://mq/
    links:
      - mq
    depends_on:
      - mq
